version: '3.8'

services:

  authserver:
    image: nginx:latest
    links:
      - authcode
    ports:
      - "8080:80"
    volumes:
      - ./code:/usr/share/nginx/html/
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/authserver

  authcode:
    build:
      context: ./dockerfiles/php
    links:
        - postgres
    volumes:
      - ./code:/usr/share/nginx/html/
      - ./code.ini:/usr/local/etc/php/conf.d/code.ini

  authcomposer:
    image: composer:latest
    command: ["composer", "create-project", "laravel/lumen", "."]
    volumes:
        - ./code:/app

  postgres:
      image: postgres
      volumes:
          - ./default.sql:/docker-entrypoint-initdb.d/default.sql
      environment:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: auth
          PGDATA: /var/lib/postgresql/data/pgdata
